### ISSUE TITLE
simply comparing todo and todo done does not work

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#35]
when comparing the todo and the done code it needs more than just a text compare. Write a function for it

**Comment by urapadmin** [comment]
ja, that bug entry hurts. I think it is referring to the registration UI and the current state of a collected material.

**Comment by urapadmin** [comment]
while the observation is correct: Just comparing them on a text level would not suffice to signal whether or not there is something left to do. But I can't see where I do that, so I don't know where to change what. 
-> not_in_v1

**Comment by urapadmin** [comment]
Ah, there: One can select "something left to do" and that refers to a field named "calc_done_equals_todo". 
And there I should at least throw away all "!" and then check if every character in todo appears in done.

**Comment by urapadmin** [comment]
### @test 10.8.2
This is about the registration for collected material (registrar and specialists/collected material).

First of all something about registration codes - for the user's manual: 
- valuelist_registration_status must be configured in a way that every status is represented by a single character. And don't user case-sensitivity here. An upper T and a lower t will be the same later on. You list all valid combinations of registration codes here line per line:
>H
HR
HRS
HW
HWC
HWCP
HWCD
HRP
HRD
HRDP

- while this valuelist contains all possible combinations of codes, the codes themselves have to be configured in general/registration_codes_done and general/registration_codes_todo. 
- registration_codes_todo is allowed to have codes with an additional exclamation mark that signals a marked subject has priority in processing. So "C!" for instance is the same as "C" but with priority. You have to list all codes that can have a priority mark explicitly in "registration_codes_todo": 

> H=Expected back from the field
R=to be registered
C=Ceramics need processing
C!=Priorized Ceramics Processing
W=to be washed
P=to be photographed
S=to be sieved
D=to be drawn

- in registration_codes_done no exclamation marks are allowed because a todo C! is met with a C.

If this is correctly configured and the mentioned conventions are met (most of them are not programmatically enforced but the system relies on them), the registration understands if all todos for a collected material are done.

This has relevance only for the view "something left to do":

- [ ] the list should only contain collected material where at least one todo code is not met by a done code. 
- [ ] it should not matter that there are more done codes than todo codes as long as all todo codes are within the done codes
- [ ] the order of the codes should not make a difference. If you manage to input "DC" in todo and it is "CD" in done this still counts as done. But to manage such an input you have to use the tab key in todo. Otherwise the DC will be turned into CD.
- [ ] An exclamation mark in the to do field will not be interpreted. So if you have todo "DC!" and done "CSD" this cm is done and should disappear from the list

**Comment by luizaogs** [comment]
Everything seems to be working.

Of relevance for the user's manual, because it took me forever to figure it out: the heart refreshes the page.

**Comment by urapadmin** [comment]
no, it doesn‘t. Or rather it does but only as a side effect. The heart sets the date filter to the current season.

**Comment by luizaogs** [comment]
Ha, funny. Then how does one refresh? By switching views? The done CM are not disappearing by themselves, hence my search for a refresh button.

**Comment by urapadmin** [comment]
I‘d say you are our first registrar who realizes that she is missing a refresh button :) I will make one.

**Comment by luizaogs** [comment]
I keep giving you more things to do! Sorry.

**Comment by urapadmin** [comment]
since we already have a users-manual tag: The date that is set as a filter when clicking on the hear button is configured in general/season_date and has to be a valid date and(!) time. 

There was also a problem with the field in the config which I have patched with v11. But with the patch the season_date is wiped out so please set it afresh.

**Comment by luizaogs** [comment]
Well, thank you for the button :) And for giving me an excuse to stop reading about damn Mesopotamia for 10 minutes ... 

I feel like I should be giving you something on your last official day as a research assistant, but instead I give you a dumb question: what is the correct format for the date and time in configuration? I couldn't find it in the wiki.

**Comment by urapadmin** [comment]
oh, but you already gave me an enigmatic quote, remember? 
"Der Wahnsinn, Gegenstand meiner Untersuchungen, war bisher eine Insel, verloren im Ozean der Vernunft; ich beginne zu vermuten, dass es ein ganzer Erdteil ist."
Now I own this nice Suhrkamp edition of the Machado de Assis novella in not any longer mint condition. 

But you had a question:
I am not sure. Here I was able to use European date dd.mm.yyyy hh:mm as well as american mm/dd/yyyy hh:mm. It might depend on your regional settings.

**Comment by luizaogs** [comment]
American worked for me, didn't try European because I am lazy.

Ah yes -- that looks quite different in German, doesn't it? And well, as long as the book isn't stinky! (I kinda like stinky books, though I prefer to think of them as "vintage" rather than "stinky".)

**Comment by urapadmin** [comment]
I have to wash my hands after vintage :o) but I really was lucky. Somebody had the book on the shelf but never in her hands. It was really like new. And we make good books (much unlike the Brits and the Americans), so no acid or anything browned the pages. Happy :o)

**Comment by luizaogs** [comment]
Ha. Good!! I too am not a huge fan of American book-making. Brazilian paper tends to be much better.
