### ISSUE TITLE
get rid of filemaker security

### ISSUE THREAD

**Issue by urapadmin** [urapadmin/kiosk#378]
no logins in filemaker itself. Instead there should be a login screen as the first screen when starting the database. It also affects export to filemaker and import from filemaker as they are login in to filemaker. 

Perhaps it is even possible to still use the filemaker security for admin purposes but login automatically when the database is just started without particular command line parameters?

**Comment by urapadmin** [comment]
### @test
modified_by is now set according to our own log in and not any longer with the AccountName of filemaker. 
That means these record types have to be tested again in filemaker:
- [ ] collected_material

test if the logged in user is set on creation as well as on modification of those record types.

**Comment by urapadmin** [comment]
### @test
We have buttons to set the current user as a field value:
- [ ] excavating
- [ ] simple excavating
- [ ] edit locus
- [ ] daily narratives
- [ ] feature recording
- [ ] survey recording
- [ ] small find
- [ ] site note
- [ ] unit configuration
- [ ] bugs and features

**Comment by urapadmin** [comment]
### todo
-[ ] if there is no admin user, kiosk needs to create it before forking. This cannot happen in filemaker. 
-[ ]  show the login page first and then the error page - should there be errors
-[ ] that way it should also be guaranteed that the "enter anyway buttons" are only visible after a user properly logged in.

**Comment by urapadmin** [comment]
@test
- [ ] admin features are accessible either because one has logged in to the app as admin OR because one is logged in to filemaker as admin (that still works!). To force filemaker to open its own login page during startup, open the database while pressing left SHIFT. On apple it is the OPTION key and in iOS it is more complicated: [[https://support.claris.com/s/article/How-to-make-a-login-screen-appear-for-a-FileMaker-Pro-file-that-has-been-set-to-auto-login-1503693017789?language=en_US]]
- [ ] development features are only accessible to the filemaker user lkh.

**Comment by lbestock** [comment]
Site: purpose is not updated.

**Comment by lbestock** [comment]
What is "images"? Most kinds of images are given separate checkboxes.
Locus relation images is not on the checkbox list but works (it isn't a separate modified by field from the relationship as a whole, but either changing the relationship or changing the image changes the modified by).
Dayplans can't be tested because they do not show modified by. The date on the dayplan does not change if the description of it changes (good - it shouldn't) nor if the image is replaced with a new one (not sure how I feel).
Site note photo does not have its own modified by field; neither adding a new photo nor updating an existing photo updates the sites notes modified by.

**Comment by lbestock** [comment]
Tags do not have "modified by" when accessed through the registrar page for "define tags".
Adding a tag does not result in a change in "modified by" of the locus interpretation page where it is added (and there is no separate modified by for the tags/text on that tab).
Not on the list above: interpretation. Works properly (for text changes, not tags as noted above).
There is no "modified by" in inventory (where in fact it might be quite useful).

**Comment by lbestock** [comment]
The locus information on the locus behaves half like a usual "modified by" and half not and does it need discussion? The issue is "recorded by". This is NOT created by - it is changeable in the locus record. And there is no created by attached to the locus. I also note that the "recorded by" is that field which is visible without clicking when one is in the locus list of excavating, but the "modified by" is (as standard elsewhere) what is visible if one is in the locus record itself. In neither case is it possible to see who created the record.

**Comment by lbestock** [comment]
"Locus types" is an admin thing with no modified by field so nothing to test. All the standard locus types have been tested in excavating.

**Comment by lbestock** [comment]
Neither pottery nor pottery images has a visible modified by.

**Comment by lbestock** [comment]
Simple excavating does not show the same "recorded by" field that normal excavating does in the locus list.
I am not sure why excavating and simple excavating are separate boxes for the "input current user button" testing? The button is there at unit creation, not elsewhere, and unit creation is the same whether one is in simple excavating or not.
"Bugs and features" it's not a button like elsewhere but rather automatically infilled with the current user (but can be changed by a dropdown list). I think that's fine?

**Comment by lbestock** [comment]
That above is the result of testing the checkboxes. Lots of unchecked boxes but almost all because of some reason other than simply not working.

Moving on to the last bit, I cannot get iOS to open the database in the way this says I should be able to, to sign in as admin at the FM level first. Nor in fact will it let me in as lkh, says it's an unregistered user. This is PVD from the local server 10.0.1 FMGo18 still.

**Comment by urapadmin** [comment]
if FM GO does not let you open the database with explicit credentials, then that's how it is. It does not matter. Test that bit on the Mac, then, please. There it might matter more, one day.

**Comment by urapadmin** [comment]
> 
> 
> What is "images"? Most kinds of images are given separate checkboxes.
in fact ALL images have separate checkboxes. But those are for the record that connects the image with the context (dayplan, locus_photo etc.). If the image itself is modified (by replacing it and, of course when inserting a new image), it in and of it self gets a modified_by information. That one you would see only in the gallery, where you look at the image itself.

**Comment by urapadmin** [comment]
> 
> 
> That above is the result of testing the checkboxes. Lots of unchecked boxes but almost all because of some reason other than simply not working.
> 
> Moving on to the last bit, I cannot get iOS to open the database in the way this says I should be able to, to sign in as admin at the FM level first. 
This is what works with me: You open filemaker go and you tap on the urap2021 database icon and hold until the little context menu apears. There it says "sign in..."

**Comment by urapadmin** [comment]
> Dayplans can't be tested because they do not show modified by. The date on the dayplan does not change if the description of it changes nor if the image is replaced with a new one.

- [ ] dayplans now have the modification information exposed with the usual label instead of the date when the photo was shot. Now they can be tested in the way expected in this ticket.

**Comment by urapadmin** [comment]
> Locus images DO change the modified by even if only the description is changed. Which I consider as working properly in that instance.
- [ ] That is correct.

**Comment by urapadmin** [comment]
> Site note photo does not have its own modified by field; 
- [ ] It has now, but only in the popup. There is not enough space in the list.
neither adding a new photo nor updating an existing photo updates the sites notes modified by.
- [ ] that is correct. Since we have more than one photo they are in separate records and the modified_by belongs to that record only.

**Comment by urapadmin** [comment]
> Tags do not have "modified by" when accessed through the registrar page for "define tags".
- [ ] You can see the modified / modified_by now in test mode in red on the left side. I don't add the usual label here.

> Adding a tag does not result in a change in "modified by" of the locus interpretation page where it is added 
> (and there is no separate modified by for the tags/text on that tab).

- [ ] You can see the modified_by field now in test mode in red behind the tag name. I will not add the usual label here.

> Not on the list above: interpretation. 
- [ ] Interpretation is just a field of the locus record. So what you see is the modification information of the locus.

> There is no "modified by" in inventory (where in fact it might be quite useful).
- [ ] now there is one

**Comment by urapadmin** [comment]
> 
> The locus information on the locus behaves half like a usual "modified by" and half not and does it need discussion? The issue is "recorded by". This is NOT created by - it is changeable in the locus record. And there is no created by attached to the locus. I also note that the "recorded by" is that field which is visible without clicking when one is in the locus list of excavating, but the "modified by" is (as standard elsewhere) what is visible if one is in the locus record itself. In neither case is it possible to see who created the record.

I turn this into a separate ticket

**Comment by urapadmin** [comment]
### @test 10.3.6
This is a huge mess. I have given you checkboxes for everything I did or commented on and singled out one ticket. If all checkboxes are checked, we should be done here.

**Comment by lbestock** [comment]
![image](https://user-images.githubusercontent.com/49291909/110720005-da95bf80-81db-11eb-84ce-ecbd64043e19.png)

> > Adding a tag does not result in a change in "modified by" of the locus interpretation page where it is added
> > (and there is no separate modified by for the tags/text on that tab).
> 
> * [ ]  You can see the modified_by field now in test mode in red behind the tag name. I will not add the usual label here.

This doesn't show the date, just the person. (I also am concerned about "admin" - Luiza is unlikely to have logged in as admin, I think. But I just created a new one as me and at least it got the person right.)

**Comment by lbestock** [comment]
Just one left, otherwise all checked.

**Comment by urapadmin** [comment]
This does not show the date because we are testing modified_by here. If you think the correct person is used in the modified_by field, this can be closed. The label is really just a test label and should not be visible without the test mode on.
