### ISSUE TITLE
Consolidating User's Manual Tickets

### ISSUE THREAD

**Issue by SamKimball-BrownU** [urapadmin/kiosk#835]
This ticket is intended to get all the things that need to go into the user's manual in one place. I would do it on the wiki, but the fact that it is a specific task (although not a software related one) makes me think ticket. Plus, check boxes are very helpful, and I wanted to put this in a place where the info could be accessed by others.

**Comment by SamKimball-BrownU** [comment]
**User's Manual:**

- [ ] make it clear that there are many ways to do most of the things, but only some are supported/best practice #689 

- [ ] image uploading. important. #701 

- [ ] pinboard! useful feature, but new. Not fully implemented. Just needs a section for itself, with a sufficient explanation #709 

- [ ] what is a small find, when to use it, be careful of it. approval process. #729 

- [ ] dayplans/narrative link is something that happens passively. The user doesn't have to do anything. But, useful for analysis. Probably just put in admin guide, although perhaps useful for some users. I will bring this up. #739 #749 

- [ ] Landscape vs vertical orientation. What do we support, how to lock into landscape. #769 

- [ ] how to PROPERLY use tagging #823, #828 

- [ ] God this is a big one. Need to somehow communicate the philosophy of the system. Perhaps beefy intro??? This was spurred by talk about replacing images #833 

**Importing images:**

- [ ] import context-less images... confusing, let's see how well I can write the instructions #832 

- [ ] naming import images/files #811 

- [ ] how to import images #714 

- [ ] How to upload qr photos. This goes more generally to file upload, BUT I do need to make sure to give guidance on how to take a proper photo so that kiosk can process it. Particularly, make sure there isn't glare on it. #750 

**Admin Guide:**

- [ ] resetting passwords - Admin guide #699 

- [ ] How updates are rolled out. Admin Guide. #770 

- [ ] When to use admin account, what it should look like. Admin guide again. #778 

- [ ] Workaround for photoshop bug. Put it in admin guide. #732 Perhaps we need a troubleshooting section?

- [ ] Back end of synchronization. Put in admin guide #735 

- [ ] admin guide: how to fix broken images/other mistakes like it #701 

- [ ] #753 uhhhhhhh idk what this ticket is even. Seems registrar/admin-ish to me. 

- [ ] Configuration constant - QR code substitution issue. To admin guide. #760 

- [ ] Overall, how to fix mistakes/problems/bugs will be a big section in admin guide

**Comment by SamKimball-BrownU** [comment]
I have also included all of the notes from https://www.meritaten.net/urapdev/doku.php?id=sam_s_notes

**Comment by SamKimball-BrownU** [comment]
And now all of the issues from our team discussions are included

**Comment by SamKimball-BrownU** [comment]
and now from the comments in the wiki

**Comment by SamKimball-BrownU** [comment]
@lbestock if you ever want to add some tasks for the user manual, here is a great place to do it
